# Generated by Django 5.2.4 on 2025-09-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_specification_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام جشنواره')),
                ('discount_percentage', models.PositiveIntegerField(verbose_name='درصد تخفیف')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(choices=[(0, 'بدون تخفیف'), (10, '۱۰٪'), (20, '۲۰٪'), (30, '۳۰٪'), (50, 'تخفیف ویژه ۵۰٪'), (60, 'تخفیف ویژه ۶۰٪'), (80, 'تخفیف ویژه ۸۰٪')], default=0, verbose_name='تخفیف'),
        ),
    ]
