# Generated by Django 5.2.4 on 2025-09-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_festival_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_duration',
            field=models.IntegerField(blank=True, choices=[(2, '۲ ساعت'), (24, '۲۴ ساعت'), (48, '۴۸ ساعت')], null=True, verbose_name='مدت زمان تخفیف (ساعت)'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='شروع تخفیف'),
        ),
    ]
